<?php
define('DBHOST', 'localhost');
define('DBUSER', 'root');
define('DBPASS', '');
define('DBNAME', 'volleyball');

define("SITE_NAME", "KametSportsEvent");
define("SESSION_ALIAS", "KametSports");
define('SITE_URL', "http://" . $_SERVER['HTTP_HOST'] . "/KametSportsEvent/");
define('ADMIN_URL', $_SERVER['DOCUMENT_ROOT'] . "/KametSportsEvent/admin/");
define('DOCUMENT_ROOT', $_SERVER['DOCUMENT_ROOT'] . "/KametSportsEvent/");
define("COMPANY_NAME", "KametSportsEvent");
define("COPYRIGHT", "&copy Copyright 2015 - All Rights Reserved ( Safari info soft. )");
define("INVALID_CAPTCHA", "Please enter correct captcha");
define("VALID_CAPTCHA", true);
define("ROWS_PER_PAGE", 5);
define("ITEMS_PER_PAGE", 12);
define("EMAIL_TO", "fevicolfevicol@gmail.com");
define('CreatedIP',$_SERVER['REMOTE_ADDR']);
define("CONTACT_EMAIL", "pateldavid33@gmail.com");
define("CONTACT_PASSWORD", "cariblist");
define("EMAIL_FOOTER", "With Best Regards,<br>.<br><br>");
//small>Note: Please do not reply or forward this email.<br>If you are not associated with this email, please ignore and delete.</small>


//EMAIL FORMATE START
$header = '';
$header .= '<!DOCTYPE html>';
$header .= '<html>';
$header .= '<head>';
$header .= '<meta charset="UTF-8">';
$header .= '<title>Kamet Sports Events</title>';
$header .= '</head>';
$header .= '<body>';
$header .= '<div id=":1re" class="a3s" style="overflow: hidden;"><u></u>';
$header .= '<div style="width:100%;min-height:100%;padding:0;background-color:#ffffff;font-family:Arial,Tahoma,Verdana,sans-serif;font-weight:299px;font-size:13px;text-align:center" bgcolor="#ffffff">';
$header .= '<table style="max-width:810px;border-left:solid 1px #104A9C;border-right:solid 1px #104A9C; border-top:solid 1px #104A9C;" width="100%" cellpadding="0" cellspacing="0">';
$header .= '<tbody>';
$header .= '<tr>';
$header .= '<td style="width:10px;background-color:#EBEBEB" width="10" bgcolor="#D4D1D1">&nbsp;</td>';
$header .= '<td style="background-color:#EBEBEB;padding:0;margin:0" align="left" valign="middle" height="50" bgcolor="#D4D1D1">';
$header .= '<a style="text-decoration:none;outline:none;color:#ffffff;font-size:13px" href="'.SITE_URL.'" target="_blank">';
$header .= '<img class="CToWUd" src="'.SITE_URL.'admin/image/Logo/KLogo.png" alt="kametsportsevent.com" style="border:none" height="45" border="0">';
$header .= '</a>';
$header .= '</td>';
$header .= '<td style="width:10px;background-color:#EBEBEB" width="10" bgcolor="#D4D1D1">&nbsp;</td>';
$header .= '</tr>';
$header .= '</tbody>';
$header .= '</table>';
//EMAIL Body Start
$BodyStart = '';
$BodyStart .= '<table style="max-width:810px;border-left:solid 1px #104A9C;border-right:solid 1px #104A9C" width="100%" cellpadding="0" cellspacing="0">';
$BodyStart .= '<tbody><tr>';
$BodyStart .= '<td style="color:#2c2c2c;line-height:20px;font-weight:300;margin:0 auto;clear:both;background-color:#ffffff;padding:20px 20px 0 20px" align="left" valign="top" bgcolor="#ffffff">';
$BodyStart .= '<p style="padding:0;margin:0;color:#565656;font-size:13px">';
//EMAIL Body Ends
$BodyEnd = '';
$BodyEnd .= '</p>';
$BodyEnd .= '</td>';
$BodyEnd .= '</tr>';
$BodyEnd .= '<tr>';
$BodyEnd .= '<td style="color:#2c2c2c;line-height:20px;font-weight:300;margin:0;clear:both;background-color:#fff;padding:10px 20px 0 20px;font-size:13px" align="center" valign="top" bgcolor="#F9F9F9">';
$BodyEnd .= '</td>';
$BodyEnd .= '</tr>';
$BodyEnd .= '</tbody>';
$BodyEnd .= '</table>';
//EMAIL Footer 
$footer = '';
$footer .= '<table style="max-width:810px;border-left:solid 1px #104A9C;border-right:solid 1px #104A9C;border-bottom:solid 1px #104A9C" width="100%" cellpadding="0" cellspacing="0">';
$footer .= '<tbody>';
$footer .= '<tr>';
$footer .= '<td style="text-align:left;background-color:#FF9800;display:block;margin:0 auto;clear:both;padding:5px 20px" valign="top" bgcolor="">';
$footer .= '<p style="padding:0;margin:0 0 4px 0;font-size:12px;color:#fff"><b>DISCLAIMER</b></p>';
$footer .= '<p style="padding:0;margin:0;font-size:9px;color:#fff;line-height:15px">';
$footer .= 'The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material which is the intellectual property of Kamet Sports Events. If you are not the intended recipient, or the employee, or agent responsible for delivering the message to the intended recipient and/or if you have received this in error, please contact the Kamet Sports Events or delete the material from the computer or device.';
$footer .= '</p>';
$footer .= '</td>';
$footer .= '</tr>';
$footer .= '<tr>';
$footer .= '<td style="text-align:center;background-color:#FF9800;display:block;margin:0 auto;clear:both;padding:5px 20px" align="center" valign="top" bgcolor="">';
$footer .= '<p style="padding:0;margin:0 0 4px 0">';
$footer .= '<a title="kametsportsevent.com" style="text-decoration:none;color:#104a9c" href="'.SITE_URL.'" target="_blank"><span style="color:#104a9c;font-size:13px">kametsportsevent.com</span></a>';
$footer .= '</p>';
$footer .= '<p style="padding:10px 0 0 0;margin:0;border-top:solid 1px #104A9C;font-size:11px;color:#565656">';
$footer .= '</p>';
$footer .= '</td>';
$footer .= '</tr>';
$footer .= '<tr>';
$footer .= '</tbody></table>';
$footer .= '</td>';
$footer .= '</tr>';
$footer .= '</tbody>';
$footer .= '</table>';
define('MAIL_HEADER', $header);
define('BODY_START', $BodyStart);
define('BODY_FOOTER', $BodyEnd);
define('MAIL_FOOTER', $footer);

//EMAIL FORMATE END




//MENU LIST
define("home", 'Dashboard');
define("view_location", 'Location');
define("CountryName", 'Country Name');
define("StateName", 'State Name');
define("SelectStateToTournament", 'Select State to Apply for Tournament');
define("AreaName", 'Area Name');
define("ClassName", 'Class Name');
define("OwnerName", 'Owner Name');
define("PhoneNo", 'Phone No');
define("ClassTagLine", 'Class Tag Line');
define("ClassOwnerName", 'Owner Name');
define("ClassEmailID", 'Class Email ID');
define("ClassPhoneNo", 'Class Phone No');
define("ClassLandLineNo", 'Class Landline No');
define("LandLineNo", 'Landline No');
define("ClassLogo", 'Class Logo');
define("ClassDescription", 'Class Description');
define("CityName", 'City Name');
define("SelectCityToTournament", 'Select City to Apply for Tournament');
define("ROW_ACTION", 'Action');
define("SrNo", 'Sr. No.');
define("update", 'Update');
define("back", 'Back');
define("UserType", 'User Type');
define("KWName", 'Keyword Name');
define("KWID", 'Keyword ID');
define("save", 'Save');
define("view_all", 'View All');
define("add_new", 'Add New');
define("Fname", 'First Name');
define("Mname", 'Middle Name');
define("Lname", 'Last Name');
define("email", 'Email ID');
define("reason", 'Reason');
define("password", 'Password');
define("SQuestion", 'Security Question');
define("SMName", 'Social Media Name');
define("SMDescription", 'Social Media Description');
define("SMImage", 'Social Media Image');
define("dob", 'Date Of Birth');
define("Gender", 'Gender');
define("Bdate", 'Birth Date');
define("store_name", 'Store Name');
define("cell_number", 'Mobile Number');
define("land_number", 'Landline Number');
define("OfficeAddress1", ' Address Line 1');
define("OfficeAddress2", ' Address Line 2');
define("AddressLine1", 'Address Line #1');
define("AddressLine2", 'Address Line #2');
define("ZIPCode", 'ZIP Code');
define("about_me", 'About You');
define("MobileNumber", 'Mobile Number');
define("about_description", 'About Description');
define("return_description", 'Return Description');
define("company_name", 'Company Name');
define("address", 'Address');
define("phone_no", 'Phone No.');
define("fax", 'Fax');
define("zipcode", 'ZIP Code');
define("SliderHeading", 'Slider Heading');
define("SliderText", 'Slider Text');
define("SliderImage", 'Slider Image');
define("SliderTitle", 'Slider Title');
define("SliderDescription", 'Slider Description');
define("faq_question", 'Question');
define("faq_answer", 'Answer');
define("term_description", 'Term & Description');
define("privacy_content", 'Privacy Content');
define("CatName", 'Category Name');
define("CatDesc", 'Category Description');
define("SubCatName", 'SubCategory Name');
define("SubCatDesc", 'SubCategory Description');
define("PKSrNo", 'Keyword ID');
define("PKName", 'Keyword Name');
define("PKDesc", 'Keyword Description');
define("MfgName", 'Mfg. Name');
define("MfgDesc", 'Mfg. Description');
define("SizeName", 'Size Name');
define("SizeDesc", 'Size Description');
define("AttackName", 'Attack Name');
define("AttackDescription", 'Attack Description');
define("DocumentTitle", 'Document Title');
define("FormationName", 'Formation Name');
define("FormationDescription", 'Formation Description');
define("LevelName", 'Level Name');
define("LevelDescription", 'Level Description');
define("Question", 'Question');
define("UsersName", 'Users Name');
define("UserName", 'User Name');
define("FirstName", 'First Name');
define("MiddleName", 'Middle Name');
define("LastName", 'Last Name');
define("NickName", 'Nick Name');
define("CaptainshipStatus", 'Captain');
define("ProfilePicture", 'Profile Picture');
define("ProofID", 'Proof ID');
define("IDProof", 'ID Proof');
define("Aprrove", 'Aprrove');
define("Decline", 'Decline');
define("TournamentName", 'Tournament Name');
define("TypeName", 'Tournament Type Title');
define("Description", 'Description');
define("TournamentFor", 'Tournament For');
define("RegistrationFees", 'Registration Fees');
define("Location", 'Location');
define("TournamentAddress", 'Tournament Address');
define("RunnerUpsPrize", 'RunnerUp Prize');
define("WinnerPrize", 'Winner Prize');
define("TeamName", 'Team Name');
define("TeamSlogan", 'Team Slogan');
define("CaptainName", 'Captain Name');
define("TeamCode", 'Team Code');
define("TeamDescription", 'Team Description');
define("State", 'State');
define("City", 'City');
define("Area", 'Area');
define("TeamLogo", 'Team Logo');
define("PlayerName", 'Player Name');
define("PlayerStatus", 'Player Status');
define("Tournament", 'Tournament');
define("TournamentType", 'Tournament Type');
define("SearchCountry", 'Search Country');
define("SearchState", 'Search State');
define("SearchCity", 'Search City');
define("StartDate", 'Tournament Start Date');
define("EndDate", 'Tournament End Date');
define("RegistrationStartDate", 'Registration Start Date');
define("RegistrationEndDate", 'Registration End Date');
define("PlayerOfTheTournamnetPrice", 'Player Of The Tournament Prize');
define("SecondRunnerUpsPrize", 'Second Runner Ups Prize');
define("TournamentImage", 'Tournament Image');
define("TournamentRules", 'Tournament Rules');
define("MaximumPlayers", 'Maximum Players');
define("MinimumPlayers", 'Minimum Players');
define("SelectTournament", 'Select Tournament');
define('GroupName','Group Name');
define('GroupDescription','Group Description');
define('AdminApproval','Approve By Admin');
define('RoundName','Round Name');
define('TournamentDescription','Tournament Description');
define('NumberOfGamesToPlay','Number Of Games To Play');
define('PlayMatchType','Play Match Type');
define('SetTitle','Set Title');
define('NoOfSets','Number Of Sets');
define('SearchTournament','Search Tournament');
define('SelectTournament','Select Tournament');
define('SelectPlayers','Select Players');
define('GamesWonPoints','Games Won Points');
define('GamesLostPoints','Games Lost Points');
define('TotalPoints','Total Points');
define('NumberOfSetsToPlay','Number Of Sets To Play');
define('CourtName','Court Name');
define('Round','Round');
define('GroupA','Group A');
define('GroupB','Group B');
define('MatchType','Match Type');
define('MatchStartTime','Match Start Time');
define('MatchDate','Match Date');
define('MatchDescription','Match Description');
define('MatchVenue','Match Venue');
define('GroundName','Ground Name');
define('MatchSchedule','Match Schedule');
define('NumberOfSets','Number Of Sets');
define('SelectPlayer','Select Player');
define('SendRequestToBecomeCaptain','Send Request To Become Captain');
define('WinningTeamName','Winning Team Name');
define('LosingTeamName','Losing Team Name');
define('NotificationsToJoinTeam','Team Join Notifications');
define('TotalMatchPlayed','Total Match Played');
define('TotalMatchWon','Total Match Won');
define('TotalMatchLoose','Total Match Loose');
define('NumberOfSetsWin','Number Of Sets Win');
define('NumberOfSetsLoose','Number Of Sets Loose');
define('MatchResult','Match Result');
define('CoachName','Coach Name');
define('TotalMatchAbandoned','Total Match Abandoned');
define('MatchWith','Played With (Team Name)');
?>

